#BlueJ class context
comment0.target=EnemigoLaser
comment1.params=
comment1.target=EnemigoLaser()
comment10.params=
comment10.target=void\ crearLaser()
comment11.params=
comment11.target=void\ eliminarAlerta()
comment12.params=
comment12.target=void\ eliminarLaser()
comment13.params=
comment13.target=void\ limpiarObjetosLaser()
comment14.params=
comment14.target=void\ alSerDestruido()
comment2.params=
comment2.target=void\ crearImagen()
comment3.params=
comment3.target=void\ actualizarComportamiento()
comment4.params=
comment4.target=void\ entrar()
comment5.params=
comment5.target=void\ cargar()
comment6.params=
comment6.target=void\ dispararLaser()
comment7.params=
comment7.target=void\ escapar()
comment8.params=velocidad
comment8.target=void\ moverVertical(int)
comment9.params=
comment9.target=void\ crearAlerta()
numComments=15
