#BlueJ class context
comment0.target=GameManager
comment1.params=
comment1.target=GameManager()
comment10.params=
comment10.target=int\ getProgresoTriple()
comment11.params=
comment11.target=int\ getPuntos()
comment12.params=
comment12.target=int\ getEnemigosEliminados()
comment13.params=
comment13.target=void\ terminarJuego()
comment14.params=
comment14.target=boolean\ isJuegoTerminado()
comment15.params=
comment15.target=void\ reiniciar()
comment16.params=
comment16.target=void\ notificar()
comment2.params=
comment2.target=GameManager\ getInstancia()
comment3.params=o
comment3.target=void\ suscribir(Observador)
comment4.params=p
comment4.target=void\ sumarPuntos(int)
comment5.params=puntosGanados\ cargaGanada
comment5.target=void\ registrarEnemigoDestruido(int,\ int)
comment6.params=
comment6.target=boolean\ activarTriple()
comment7.params=
comment7.target=void\ actualizarTriple()
comment8.params=
comment8.target=boolean\ isTripleActivo()
comment9.params=
comment9.target=boolean\ isTripleListo()
numComments=17
